# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Anify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  API_KEY: temp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1

    - run: bun run install
    - run: bun run lint
    - run: bun run build
